#ifndef   __NOVEMBERIZING_X__CLIENT__SOCKET_EVENT_TYPE__H__
#define   __NOVEMBERIZING_X__CLIENT__SOCKET_EVENT_TYPE__H__

#include <x/socket/event/type.h>

#endif // __NOVEMBERIZING_X__CLIENT__SOCKET_EVENT_TYPE__H__
